### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by adacnvwp** [spatie/ignition#103]
Error: Minified React error

**Comment by AlexVanderbist** [comment]
Hi @adacnvwp, can you please open a new issue with some extra context? What were you doing when the error occurred? Can you try checking if it also happens in Incognito mode or another browser?

If you haven't done so already, you can also try running `composer update` to update Ignition or its dependencies to the latest version.

Thanks for reporting this issue and good luck!
