### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by samimcanboke** [spatie/ignition#106]
Hello Can you help me for this case ? when i scroll down into ignition page it giving this error. 

My browser console is :
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/96445882/159664714-8bcb9e37-a014-48ee-b695-53e38d09a5e1.png">

**Comment by AlexVanderbist** [comment]
Hey, can you please try upgrading to the latest version of Ignition by running `composer update`? This will improve the outputted error. Alternatively you can try opening the page in an incognito window or with extensions disabled (e.g. TronLink is known to cause issues). Please let us know if any of these possible fixes work in #107.

Finally, feel free to open a new issue if you're still experiencing this issue!
