### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by shubhamkumar78767** [spatie/ignition#108]
(User dashboard)  =>  when click on edit button  then page not open ...... it show undefined variable $user

**Comment by shubhamkumar78767** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/87086624/159689987-5ff0278c-9679-48e3-a366-a59b09d3a9d1.png)

**Comment by AlexVanderbist** [comment]
hey @shubhamkumar78767, this looks like a regular Laravel error, not something related to Ignition... Feel free to open a new issue if I'm mistaken :)
