### ISSUE TITLE
"Open in editor" doesn't work when app is run from a docker container

### ISSUE THREAD

**Issue by ddanielou** [spatie/ignition#114]
The application path as seen by Ignition doesn't necessarily correspond to the local path. One such situation is when the app is run from a docker container.

In my case, the actual files that VSCode could edit are in ~/Sites/some-website. The path, from Ignition's POV, is something like /var/www/. Setting the applicationPath obviously doesn't have the desired effect.

Perhaps adding a second argument to ``Ignition::applicationPath()`` could work? Something like:
```php
$ignition->applicationPath(applicationPath: '/var/www', replaceWith: '/Users/something/Sites/website');
```

**Comment by ddanielou** [comment]
My bad, this is configurable in ``.ignition.json.``

For other people struggling like me, here's an example of how you could configure ignition:
```json
{
    "local_sites_path": "/Users/myusername/Sites/mywebsite/public",
    "remote_sites_path" : "/var/www/public"
}
```

**Comment by jtomek** [comment]
where do you put the code in Laravel Sail?

**Comment by vityachis** [comment]
You can also specify variables in the `.env` file:
```
IGNITION_REMOTE_SITES_PATH="/var/www"
IGNITION_LOCAL_SITES_PATH="/Users/username/Sites/project"
```

**Comment by jtomek** [comment]
Thank you!
