### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by msbshabi** [spatie/ignition#115]
Sorry! I don't know that much about the error. It showed "**An error occurred in Ignition's UI. Please open an issue on [the Ignition GitHub repo] and make sure to include any errors or warnings in the developer console.**"

The console error as follows:
`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=symbol&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Comment by AlexVanderbist** [comment]
Hey @msbshabi, please try upgrading Ignition using following command:

```bash
composer update spatie/laravel-ignition -W
```

If that doesn't work, please check out this issue: #107
