### ISSUE TITLE
Cannot pass instances of ProvidesSolution to SolutionProviderRepository::registerSolutionProviders

### ISSUE THREAD

**Issue by DieterHolvoet** [spatie/ignition#121]
According to the `SolutionProviderRepository` contract, it should be possible to pass instances or class strings to `registerSolutionProviders`, but only class strings are supported by the contract implementation.

**Comment by AlexVanderbist** [comment]
Hi @DieterHolvoet, good catch! Do you need to pass a `ProvidesSolution` instance for a specific reason? Otherwise I'll just fix the doc block. The singular `registerSolutionProvider` does seem to be correctly typed.

**Comment by DieterHolvoet** [comment]
Passing instances would be useful. This way we can store solution providers in the dependency container. Some advantages: we can inject dependencies for more complex providers, we can provide a system for third-party modules to add solution providers, etc.

**Comment by DieterHolvoet** [comment]
@AlexVanderbist any update on this? We could still really use this fix for the Drupal module.

**Comment by AlexVanderbist** [comment]
@DieterHolvoet sorry about that! Lost track of this issue for a while. I'll look into it later this week.

**Comment by AlexVanderbist** [comment]
I've merged the necessary changes for this to `main`. I'll tag a new version later today.

Just wanted to warn about the performance impact of adding instances to the `SolutionProviderRepository`. Depending on the solution provider, creating an instance of the provider and adding that to the provider repository every time the application boots, will add a bit more overhead compared to adding a class string and only initialising it when handling an exception.

**Comment by DieterHolvoet** [comment]
Right, makes sense. Thanks for the effort! Will try it out in the Drupal module once you tag the new version.

**Comment by DieterHolvoet** [comment]
I noticed you had to revert the contract change. Not a problem for me, I only need `registerSolutionProviders` and that one doesn't need a contract change. I updated the Drupal module. Thanks for your effort!
