### ISSUE TITLE
Interface incompatibility in 1.4.0

### ISSUE THREAD

**Issue by mvisd** [spatie/ignition#162]
Hi there. Just updated to 1.4.0, got this error message:

> PHP Fatal error:  Declaration of Spatie\LaravelIgnition\Solutions\SolutionProviders\SolutionProviderRepository::registerSolutionProvider(string $solutionProviderClass): Spatie\Ignition\Contracts\SolutionProviderRepository must be compatible with Spatie\Ignition\Contracts\SolutionProviderRepository::registerSolutionProvider(Spatie\Ignition\Contracts\HasSolutionsForThrowable|string $solutionProvider): Spatie\Ignition\Contracts\SolutionProviderRepository in .../vendor/spatie/laravel-ignition/src/Solutions/SolutionProviders/SolutionProviderRepository.php on line 24

I guess there is just a small thing that needs to be updated. Leaving the issue here for further discussion.

**Comment by saschagysel** [comment]
Havong the same error in newest Laravel version without any special changes to the ignition part. I think this is impacting quite a lot of laravel users.

**Comment by Jubeki** [comment]
Responsible PR here: https://github.com/spatie/ignition/pull/160

**Comment by vybeauregard** [comment]
Looks like a fix just got updated in 1.4.1

**Comment by saschagysel** [comment]
Yeah thanks for the fast fix, awesome!

**Comment by mvisd** [comment]
Wow, that was quick. Thanks for the fix!
