### ISSUE TITLE
Clicking path at the top of stack trace is broken

### ISSUE THREAD

**Issue by freekmurze** [spatie/ignition#18]
Clicking this link...

<img width="914" alt="CleanShot 2022-01-18 at 10 24 25@2x" src="https://user-images.githubusercontent.com/483853/149910315-0bfaac18-2b62-414b-8ff0-3fcb89f35816.png">

Results in...

<img width="1317" alt="CleanShot 2022-01-18 at 10 24 22@2x" src="https://user-images.githubusercontent.com/483853/149910373-aae55ec5-cd4a-443d-97bc-d012130968e8.png">

**Comment by AlexVanderbist** [comment]
Fixed in f9fdd26665d13340d33bdea369b81d55eb241701
