### ISSUE TITLE
Blocked by CSP package

### ISSUE THREAD

**Issue by liamkeily** [spatie/ignition#186]
We are using https://github.com/spatie/laravel-csp on our app, which is causing ignition to display a blank page with the following console error.

`Refused to execute inline script because it violates the following Content Security Policy directive`

This seems to happen because the `<script>` and `<style>` tags injected by the Ignition package don't use `csp_nonce()`.

**Comment by liamkeily** [comment]
I can confirm that adding `nonce="<?= csp_nonce(); ?>"` to various places in https://github.com/spatie/ignition/blob/main/resources/views/errorPage.php got the error page displaying, although still a few wonky bits to chase dow

**Comment by nelsonmelecio** [comment]
I wish to re-open this hoping find a better solution.

**Comment by nelsonmelecio** [comment]
I ended up adding another middleware to take care of nonce in every inline scripts tags.
This will only trigger when a response got isClientError() or isServerError().

`
namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class AddNonceToInlineScripts
{
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        if ($response->isClientError() || $response->isServerError()) {
            $content = $response->getContent();
            $nonce = csp_nonce();
            $contentWithNonce = $this->addNonceToInlineScripts($content, $nonce);

            $response->setContent($contentWithNonce);
        }

        return $response;
    }

    protected function addNonceToInlineScripts($content, $nonce)
    {
        return preg_replace_callback('/<script(.*?)>(.*?)<\/script>/is', function ($match) use ($nonce) {
            $attributes = $match[1];
            $scriptContent = $match[2];

            if (!str_contains($attributes, 'nonce')) {
                $attributes .= " nonce=\"$nonce\"";
            }

            return "<script$attributes>$scriptContent</script>";
        }, $content);
    }
}
`

You can add the same approach for inline style.

Hope it helps!

**Comment by BR0kEN-** [comment]
Here is the change that integrates `ignition` with `csp` package - https://github.com/spatie/ignition/pull/462.

**Comment by lexod** [comment]
an other temporary solution would be to bind `Spatie\Ignition\Ignition` class to a custom implementation via Laravel service container which overrides `renderException()` method in order to use blade renderer so `nonce="{{csp_nonce()}}"` can be used on script/styles tags (make sure to create a blade template mimicking the one being used by ignition). 

```php
// in AppServiceProvider.php

public function register() {
  $this->app->bind(\Spatie\Ignition\Ignition::class, \App\YourCustomIgnition::class);
}

// in YourCustomIgnition.php

public function renderException(Throwable $throwable, ?Report $report = null): void
    {
        $this->setUpFlare();

        $report ??= $this->createReport($throwable);

        $viewModel = new ErrorPageViewModel(
            $throwable,
            $this->ignitionConfig,
            $report,
            $this->solutionProviderRepository->getSolutionsForThrowable($throwable),
            $this->solutionTransformerClass,
            $this->customHtmlHead,
            $this->customHtmlBody,
        );

        echo view('your.custom.template', ['viewModel' => $viewModel])->render();
        // or simply include your php file here utilizing $viewModel variable
        // include resource_path('your.custom.template');
    }
```

**Comment by BR0kEN-** [comment]
I stopped with another one temporarily:

```php
    public function shouldBeApplied(Request $request, Response $response): bool
    {
        if ((
            parent::shouldBeApplied($request, $response)
            && !$this->app->environment('testing')
            && !$request->isXmlHttpRequest()
        )) {
            // @todo PSSPP1-1793: Remove this processing when resolved.
            // https://github.com/spatie/ignition/pull/462
            if ($response->isServerError()) {
                $content = $response->getContent();

                if (\str_contains($content, '<script')) {
                    $response->setContent(
                        \preg_replace(
                            '/(<script)(.+?>)/usm',
                            "$1 nonce='".\csp_nonce()."'$2",
                            $content,
                        ),
                    );
                }
            }

            return true;
        }

        return false;
    }
```

**Comment by oprudkyi** [comment]
Hi @freekmurze 
why is it closed ? is there any solutions inside ignition ? 
or there should be used workarounds like  https://github.com/spatie/ignition/issues/186#issuecomment-1888466267
