### ISSUE TITLE
Dump location is not always correct

### ISSUE THREAD

**Issue by freekmurze** [spatie/ignition#19]
Here's an example where we dump in the controller, but the path displays the previous frame.

<img width="785" alt="CleanShot 2022-01-18 at 10 26 18@2x" src="https://user-images.githubusercontent.com/483853/149910553-9c243b82-4201-4c4a-a726-6d562edcd51a.png">

<img width="1066" alt="CleanShot 2022-01-18 at 10 26 35@2x" src="https://user-images.githubusercontent.com/483853/149910579-e5cf3162-3f73-4458-b60e-2675728c4b28.png">

**Comment by AlexVanderbist** [comment]
Fixed!
