### ISSUE TITLE
Button to expand query view is not fully visible

### ISSUE THREAD

**Issue by freekmurze** [spatie/ignition#20]
<img width="1318" alt="CleanShot 2022-01-18 at 15 10 42@2x" src="https://user-images.githubusercontent.com/483853/149953258-b00dbfef-90a5-4730-8a94-c4dcc80d1118.png">

**Comment by willemvb** [comment]
Seems this was fixed along the way!

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1336390/150302284-7b29efe2-38ff-4e1c-94c6-a142c5590c09.png">
