### ISSUE TITLE
Insomnia dose not works with the Error Page.

### ISSUE THREAD

**Issue by Jing-King** [spatie/ignition#28]
It is only showing navy blue background. I think it has to do with the browser agent, it use "insomnia/2021.7.2"

![Image_DESKTOP-N29PP9B_1643235500](https://user-images.githubusercontent.com/15640777/151257846-c1436aaa-a2d2-4846-aee2-43b485830af9.png)

![Image_DESKTOP-N29PP9B_1643235964](https://user-images.githubusercontent.com/15640777/151257636-30af9fb1-0c21-4e28-9dd0-3ec11a20b424.png)

**Comment by jusdeleon** [comment]
Hi @Jing-King did you manage to get a work around for this issue?
