### ISSUE TITLE
An error page changes the current URL structure

### ISSUE THREAD

**Issue by mgralikowski** [spatie/ignition#47]
When you get an error, your current URL is changed by adding a hash like `#F50`. 

I suppose it is added with reason, maybe some kind of JS routing but this is annoying. Especially when you refresh the page the hash still exists, so my browser history is polluted by "hashed" URLs. Also is harder to select URLs text, modify it, etc.

But what is the worst - when you use hashes in your application and you generate an error, you lost your original URL with hash, even if you fix this error and refresh the page.

**Comment by AlexVanderbist** [comment]
Hi @mgralikowski, thanks for letting us know. We'll tag `spatie/ignition:1.1.0` later today that will remove this URL hash. Running `composer update` in your Laravel project will automatically pull in this update!

Thanks for taking the time to reach out!
