### ISSUE TITLE
Symfony Exception instead of Ignition in Laravel 9

### ISSUE THREAD

**Issue by moisish** [spatie/ignition#48]
For some reason, the errors on my server don't show the ignition error page

![image](https://user-images.githubusercontent.com/15047879/155329722-414e8926-0f1c-4de6-99f6-8ddb60b34576.png)

**Comment by innocenzi** [comment]
Same thing, except I don't even have content. 

![](https://i.imgur.com/39U7SEC.png)

**Comment by innocenzi** [comment]
Looks like the error comes from here: https://github.com/spatie/ignition/blob/e8993b2d1b49d30ddba8827f769013fadbbb8a9b/resources/views/errorPage.php#L26

![](https://i.imgur.com/lPn59pq.png)

**Comment by innocenzi** [comment]
Related to this actually: https://github.com/spatie/laravel-ignition/issues/35

**Comment by jazerix** [comment]
This too is happening in my application after upgrading my Laravel application from 8 -> 9 today. Some exceptions seem to show the new page fine, others just trigger what others have posted:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4068103/155611163-1df5bd1b-eb97-4bfd-b3a7-c062476ecdaa.png">

Specifically, in my case, I was trying to `dd` a property on an object that didn't exist.

**Comment by moisish** [comment]
The problem seems to be on this line https://github.com/spatie/flare-client-php/blob/main/src/Report.php#L323

On the laravel application @jazerix created if you encode and dump the stracktrace it returns Symfony's error page

```    
    public function toArray(): array
    {
        dd(json_encode($this->stracktraceAsArray()));

```

![image](https://user-images.githubusercontent.com/15047879/155692635-01cf3b22-6e86-491f-b570-05c04bbabbc0.png)

**Comment by jazerix** [comment]
@moisish I do think I've found the actual problem if you look at my PR #51 :)

**Comment by AlexVanderbist** [comment]
Thanks you all for your input so far. We're currently looking into this and this is a huge help. Let's continue this discussion in PR #51 👍

**Comment by AlexVanderbist** [comment]
As a quick update: I've tagged spatie/flare-client-php 1.0.3 that includes a fix for most of these issues. Running composer update will pull in this fix!

**Comment by moisish** [comment]
Thanks @AlexVanderbist
