### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.code_snippet')

### ISSUE THREAD

**Issue by GAC74** [spatie/ignition#56]
```zE@http://10.10.10.109/:72:257090mi@http://10.10.10.109/:72:70707Ql@http://10.10.10.109/:72:122310xc@http://10.10.10.109/:72:109799_c@http://10.10.10.109/:72:109727Cc@http://10.10.10.109/:72:109590Nc@http://10.10.10.109/:72:106584hc@http://10.10.10.109/:72:103960nu@http://10.10.10.109/:72:119818@http://10.10.10.109/:72:121189Oc@http://10.10.10.109/:72:106961cu@http://10.10.10.109/:72:121175render@http://10.10.10.109/:72:128585@http://10.10.10.109/:72:508570global code@http://10.10.10.109/:76:18```

**Comment by AlexVanderbist** [comment]
Hi, thanks for letting is know. This looks like a duplicate of #59. We'll continue the issue there!
