### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by Spir** [spatie/ignition#71]
I had a file with char before PHP declatation. Example:
```
i<?php

namespace ...

```
Ignition was unable to correctly report the error while in my logs I had:

_Namespace declaration statement has to be the very first statement or after any declare call in the script_

**Comment by AlexVanderbist** [comment]
Hi @Spir, we just tagged a fix for this issue: https://github.com/spatie/ignition/releases/tag/1.2.1. Running `composer update` in your project should automatically pull in this fix! Thanks for letting us know about the issue.
