### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by mbehzad-bhz** [spatie/ignition#94]
![image](https://user-images.githubusercontent.com/22252603/157728842-a0fb5144-61b5-4137-a5a5-234f7533447a.png)

**Comment by AlexVanderbist** [comment]
Hi @mbehzad-bhz, can you try to trigger this error again in an incognito window? Thanks

**Comment by AlexVanderbist** [comment]
Hey, let's continue this issue in #107
