### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by drnxloc** [spatie/ignition#95]
```TypeError: Cannot read properties of undefined (reading 'code_snippet')    at zE (http://localhost/:74:257091)    at mi (http://localhost/:74:70706)    at Ql (http://localhost/:74:122308)    at xc (http://localhost/:74:109797)    at _c (http://localhost/:74:109725)    at Cc (http://localhost/:74:109588)    at Nc (http://localhost/:74:106582)    at hc (http://localhost/:74:103958)    at nu (http://localhost/:74:119816)    at http://localhost/:74:121187```

**Comment by AlexVanderbist** [comment]
Hi @drnxloc, If you haven't done so already, you can also try running `composer update` to update Ignition or its dependencies to the latest version. This error looks a lot like one fixed a couple weeks ago.

If the error persists, can you please open a new issue with some extra context? What were you doing when the error occurred? Can you try checking if it also happens in Incognito mode or another browser?

Thanks for reporting this issue and good luck!
