### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by ebiboy2** [spatie/ignition#96]
Ignition error page displays fine but if I click on any link or mouse up, I get the error:

Something went wrong in Ignition!
An error occurred in Ignition's UI. Please open an issue on [the Ignition GitHub repo] and make sure to include any errors or warnings in the developer console.

![image](https://user-images.githubusercontent.com/12090455/157885178-a0988fc7-ab0e-4c36-b8ec-8776ab688aa3.png)

**Comment by ebiboy2** [comment]
Ignition error page displays fine but if I click on any link or mouse up, I get the error
Something went wrong in Ignition!

An error occurred in Ignition's UI. Please open an issue on [the Ignition GitHub repo] and make sure to include any errors or warnings in the developer console.

![image](https://user-images.githubusercontent.com/12090455/157885178-a0988fc7-ab0e-4c36-b8ec-8776ab688aa3.png)

**Comment by AlexVanderbist** [comment]
Hey, let's continue this issue in https://github.com/spatie/ignition/issues/107
